language: python

# Python versions to test on
python:
  - 2.7
  - 3.6
  - nightly

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov

# command to run tests
script:
  - echo Running tests and codecov ...; pytest --cov=./ -v

# Upload results to codecov
after_success:
  - echo Uploading code coverage data ...; codecov --token=74fb764a-c50f-486c-95c7-aed91ce2dfcb

notifications:
  email:
    recipients:
      - harshith9399@gmail.com
    on_success: never
    on_failure: always